In [1]:
import dask.dataframe as dd
import json
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from os import path, listdir, walk
from tqdm.notebook import tqdm
import plotly.express as px
import plotly.graph_objects as go
from sklearn import manifold
from nltk.tokenize import WordPunctTokenizer
from collections import Counter
punct_tokenizer = WordPunctTokenizer()

In [2]:
policies_dataset = pd.read_csv("./dataset/Country_Policy.csv", header = None)

In [3]:
policies_dataset

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
policies_dataset.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
policies_dataset.rename(columns = {2:'Country'})

,0,1,Country,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
policies_dataset.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
policies_dataset = policies_dataset.rename(columns = {0: 'ID', 1: 'Applies To', 2:'Country', 3: 'Starting Date', 
                                                      4: 'Ending Date', 5: 'Description of Measures Implemented', 6: 'Exceptions', 7: 'Implementing City', 
                                                      8: 'Implementing State/Province', 9: 'Keywords', 10: 'Quantity', 
                                                      11 : 'Source', 12: 'Target city', 13: 'Target country', 14: 'Target region', 
                                                      15: 'Target state'})

In [8]:
policies_dataset.head()

,ID,Applies To,Country,Starting Date,Ending Date,Description of Measures Implemented,Exceptions,Implementing City,Implementing State/Province,Keywords,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
policies_dataset = policies_dataset.drop(columns = {16,17,18,19,20,21,22,23,24,25})

In [10]:
policies_dataset.head()

,ID,Applies To,Country,Starting Date,Ending Date,Description of Measures Implemented,Exceptions,Implementing City,Implementing State/Province,Keywords,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
policies_dataset['Country'] = policies_dataset['Country'].apply(lambda row: str(row)).apply(lambda row: 'Czech Republic' if 'Czechia' in row else row)
policies_dataset['Country'] = policies_dataset['Country'].apply(lambda row: str(row)).apply(lambda row: 'United States' if 'US' in row else row)

In [12]:
policies_dataset.head()

,ID,Applies To,Country,Starting Date,Ending Date,Description of Measures Implemented,Exceptions,Implementing City,Implementing State/Province,Keywords,...,16,17,18,19,20,21,22,23,24,25
0,NaN,NaN,Afghanistan,2/24/20,NaN,"On 24 February, Afghanistan confirmed the firs...",NaN,NaN,NaN,first case,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Afghanistan,3/14/20,NaN,"President of Afghanistan, Ashraf Ghani, told t...",NaN,NaN,NaN,public announcement,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Afghanistan,3/18/20,NaN,"On 18 March, the Ministry of Interior Affairs ...",NaN,NaN,NaN,"social distancing, sports cancellation, weddin...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,NaN,Albania,3/16/20,3/26/20,Albania will close schools and ban public gath...,NaN,NaN,NaN,"first case, school closure",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,495,NaN,Albania,3/8/20,NaN,"On 8 March 2020, Albania confirmed its first t...",NaN,NaN,NaN,case reporting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
policies_dataset['Country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3           Albania
4           Albania
           ...
1701            nan
1702            nan
1703            nan
1704            nan
1705            nan
Name: Country, Length: 1706, dtype: object

In [14]:
print(policies_dataset['Country'])

0       Afghanistan
1       Afghanistan
2       Afghanistan
3           Albania
4           Albania
           ...
1701            nan
1702            nan
1703            nan
1704            nan
1705            nan
Name: Country, Length: 1706, dtype: object

In [15]:
print(f"total examples {len(policies_dataset)}")

total examples 1706

In [16]:
policies_dataset.columns

Index([                                 'ID',
                                'Applies To',
                                   'Country',
                             'Starting Date',
                               'Ending Date',
       'Description of Measures Implemented',
                                'Exceptions',
                         'Implementing City',
               'Implementing State/Province',
                                  'Keywords',
                                  'Quantity',
                                    'Source',
                               'Target city',
                            'Target country',
                             'Target region',
                              'Target state',
                                          16,
                                          17,
                                          18,
                                          19,
                                          20,
                                          21,
                                          22,
                                          23,
                                          24,
                                          25],
      dtype='object')

In [17]:
print(f"measures description found: {len(policies_dataset[policies_dataset['Description of Measures Implemented'].notnull()])}")

measures description found: 1641

In [18]:
print(f"measures keywords found: {len(policies_dataset[policies_dataset['Keywords'].notnull()])}")

measures keywords found: 1616

In [19]:
print(f"measures with date found: {len(policies_dataset[policies_dataset['Starting Date'].notnull()])}")

measures with date found: 1640

In [21]:
def check_for_mask(text):
    word_list = ['mask', 'masks']
    text = str(text)
    token = set(punct_tokenizer.tokenize(text.lower()))
    match = set(word_list).intersection(token)
    if match:
        return True
    else:
        return False

In [22]:
policies_dataset['mask'] = policies_dataset['Description of Measures Implemented'].apply(check_for_mask)

In [23]:
mask_country_count = policies_dataset[policies_dataset['mask']==True]['Country'].value_counts()

In [24]:
fig = go.FigureWidget(data = px.bar(mask_country_count, x = mask_country_count.index, y = mask_country_count.values))

In [25]:
print(mask_country_count)

South Korea       7
Hong Kong         6
China             3
Czech Republic    3
Nepal             3
Taiwan            3
Belgium           2
Japan             2
Canada            2
Italy             2
Slovakia          2
Bulgaria          1
Croatia           1
Greece            1
Egypt             1
Russia            1
Singapore         1
India             1
Sweden            1
United States     1
Name: Country, dtype: int64

In [26]:
print(mask_country_count.values)

[7 6 3 3 3 3 2 2 2 2 2 1 1 1 1 1 1 1 1 1]

In [27]:
print(mask_country_count.index)

Index(['South Korea', 'Hong Kong', 'China', 'Czech Republic', 'Nepal',
       'Taiwan', 'Belgium', 'Japan', 'Canada', 'Italy', 'Slovakia', 'Bulgaria',
       'Croatia', 'Greece', 'Egypt', 'Russia', 'Singapore', 'India', 'Sweden',
       'United States'],
      dtype='object')

In [28]:
print(mask_country_count.values)

[7 6 3 3 3 3 2 2 2 2 2 1 1 1 1 1 1 1 1 1]

In [29]:
fig.update_layout(title = 'Countries with mask mentioned in measures dataset',
                  xaxis_title = 'Country Name', yaxis_title = 'Number of events in data')
fig

FigureWidget({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'index=%{x}<br>y=%{y}<ex…