In [27]:
import dask.dataframe as dd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans

In [5]:
df = dd.read_csv("./dataset/TimeSeriesWorldCovidConfirm.csv")

In [6]:
df

Dask DataFrame Structure:
              Province/State, Country/Region  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  1/30/20  1/31/20   2/1/20   2/2/20   2/3/20   2/4/20   2/5/20   2/6/20   2/7/20   2/8/20   2/9/20  2/10/20  2/11/20  2/12/20  2/13/20  2/14/20  2/15/20  2/16/20  2/17/20  2/18/20  2/19/20  2/20/20  2/21/20  2/22/20  2/23/20  2/24/20  2/25/20  2/26/20  2/27/20  2/28/20  2/29/20   3/1/20   3/2/20   3/3/20   3/4/20   3/5/20   3/6/20   3/7/20   3/8/20   3/9/20  3/10/20  3/11/20  3/12/20  3/13/20  3/14/20  3/15/20  3/16/20  3/17/20  3/18/20  3/19/20  3/20/20  3/21/20  3/22/20  3/23/20  3/24/20  3/25/20  3/26/20  3/27/20  3/28/20  3/29/20  3/30/20  3/31/20   4/1/20   4/2/20   4/3/20   4/4/20   4/5/20   4/6/20   4/7/20   4/8/20   4/9/20  4/10/20  4/11/20  4/12/20  4/13/20  4/14/20  4/15/20  4/16/20  4/17/20  4/18/20  4/19/20  4/20/20  4/21/20  4/22/20  4/23/20  4/24/20  4/25/20  4/26/20  4/27/20  4/28/20  4/29/20  4/30/20   5/1/20   5/2/20   5/3/20   5/4/20   5/5/20   5/6/20   5/7/20   5/8/20   5/9/20  5/10/20  5/11/20  5/12/20  5/13/20  5/14/20  5/15/20  5/16/20  5/17/20  5/18/20  5/19/20  5/20/20  5/21/20  5/22/20  5/23/20  5/24/20  5/25/20  5/26/20  5/27/20  5/28/20  5/29/20  5/30/20  5/31/20   6/1/20   6/2/20   6/3/20   6/4/20   6/5/20   6/6/20   6/7/20   6/8/20   6/9/20  6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  6/15/20  6/16/20
npartitions=1
                                      object  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64
                                         ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
Dask Name: from-delayed, 3 tasks

In [7]:
df.head()

,"Province/State, Country/Region",1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20
0,"#adm1+name, #country+name",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,791.0,575.0,542.0,683.0,748.0,656.0,556.0,664.0,761.0,783.0
2,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,17.0,36.0,42.0,44.0,31.0,48.0,57.0,69.0,82.0
3,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,104.0,111.0,117.0,102.0,105.0,109.0,112.0,109.0,112.0,116.0
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [8]:
df.tail()

,"Province/State, Country/Region",1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20
262,Sao Tome and Principe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,0.0,1.0,97.0,21.0,7.0,20.0,2.0,1.0,9.0
263,Yemen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,12.0,28.0,36.0,31.0,41.0,73.0,23.0,116.0,41.0
264,Comoros,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,21.0,0.0,1.0,13.0,0.0,0.0,21.0
265,Tajikistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76.0,80.0,81.0,73.0,71.0,68.0,69.0,64.0,62.0,63.0
266,Lesotho,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [1]:
df.tail()

NameError: name 'df' is not defined

In [9]:
df[0]

KeyError: 0

In [10]:
df[1]

KeyError: 1

In [11]:
df.index(0)

TypeError: 'Index' object is not callable

In [12]:
type(df)

dask.dataframe.core.DataFrame

In [13]:
help(df.drop())

NotImplementedError: Drop currently only works for axis=1 or when columns is not None

In [14]:
help(df.drop)

Help on method drop in module dask.dataframe.core:

drop(labels=None, axis=0, columns=None, errors='raise') method of dask.dataframe.core.DataFrame instance
    Drop specified labels from rows or columns.

    This docstring was copied from pandas.core.frame.DataFrame.drop.

    Some inconsistencies with the Dask version may exist.

    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like  (Not supported in Dask)
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).

        .. versionadded:: 0.21.0
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).

        .. versionadded:: 0.21.0
    level : int or level name, optional  (Not supported in Dask)
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False  (Not supported in Dask)
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame
        DataFrame without the removed index or column labels.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),  # doctest: +SKIP
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df  # doctest: +SKIP
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)  # doctest: +SKIP
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])  # doctest: +SKIP
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])  # doctest: +SKIP
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],  # doctest: +SKIP
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],  # doctest: +SKIP
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df  # doctest: +SKIP
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')  # doctest: +SKIP
                    big
    lama    speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)  # doctest: +SKIP
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [15]:
df.dropna()

Dask DataFrame Structure:
              Province/State, Country/Region  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  1/29/20  1/30/20  1/31/20   2/1/20   2/2/20   2/3/20   2/4/20   2/5/20   2/6/20   2/7/20   2/8/20   2/9/20  2/10/20  2/11/20  2/12/20  2/13/20  2/14/20  2/15/20  2/16/20  2/17/20  2/18/20  2/19/20  2/20/20  2/21/20  2/22/20  2/23/20  2/24/20  2/25/20  2/26/20  2/27/20  2/28/20  2/29/20   3/1/20   3/2/20   3/3/20   3/4/20   3/5/20   3/6/20   3/7/20   3/8/20   3/9/20  3/10/20  3/11/20  3/12/20  3/13/20  3/14/20  3/15/20  3/16/20  3/17/20  3/18/20  3/19/20  3/20/20  3/21/20  3/22/20  3/23/20  3/24/20  3/25/20  3/26/20  3/27/20  3/28/20  3/29/20  3/30/20  3/31/20   4/1/20   4/2/20   4/3/20   4/4/20   4/5/20   4/6/20   4/7/20   4/8/20   4/9/20  4/10/20  4/11/20  4/12/20  4/13/20  4/14/20  4/15/20  4/16/20  4/17/20  4/18/20  4/19/20  4/20/20  4/21/20  4/22/20  4/23/20  4/24/20  4/25/20  4/26/20  4/27/20  4/28/20  4/29/20  4/30/20   5/1/20   5/2/20   5/3/20   5/4/20   5/5/20   5/6/20   5/7/20   5/8/20   5/9/20  5/10/20  5/11/20  5/12/20  5/13/20  5/14/20  5/15/20  5/16/20  5/17/20  5/18/20  5/19/20  5/20/20  5/21/20  5/22/20  5/23/20  5/24/20  5/25/20  5/26/20  5/27/20  5/28/20  5/29/20  5/30/20  5/31/20   6/1/20   6/2/20   6/3/20   6/4/20   6/5/20   6/6/20   6/7/20   6/8/20   6/9/20  6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  6/15/20  6/16/20
npartitions=1
                                      object  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64
                                         ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
Dask Name: dropna, 4 tasks

In [16]:
df.head()

,"Province/State, Country/Region",1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20
0,"#adm1+name, #country+name",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,791.0,575.0,542.0,683.0,748.0,656.0,556.0,664.0,761.0,783.0
2,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,17.0,36.0,42.0,44.0,31.0,48.0,57.0,69.0,82.0
3,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,104.0,111.0,117.0,102.0,105.0,109.0,112.0,109.0,112.0,116.0
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [17]:
testDf = df.dropna()

In [18]:
testDf.head()

,"Province/State, Country/Region",1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20
1,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,791.0,575.0,542.0,683.0,748.0,656.0,556.0,664.0,761.0,783.0
2,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,17.0,36.0,42.0,44.0,31.0,48.0,57.0,69.0,82.0
3,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,104.0,111.0,117.0,102.0,105.0,109.0,112.0,109.0,112.0,116.0
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
5,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,1.0,4.0,17.0,5.0,12.0,8.0,2.0,2.0,6.0

In [19]:
testDf.tail()

,"Province/State, Country/Region",1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20
262,Sao Tome and Principe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,0.0,1.0,97.0,21.0,7.0,20.0,2.0,1.0,9.0
263,Yemen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,12.0,28.0,36.0,31.0,41.0,73.0,23.0,116.0,41.0
264,Comoros,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,21.0,0.0,1.0,13.0,0.0,0.0,21.0
265,Tajikistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76.0,80.0,81.0,73.0,71.0,68.0,69.0,64.0,62.0,63.0
266,Lesotho,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
testDf.sum(axis=1)

Dask Series Structure:
npartitions=1
    float64
        ...
dtype: float64
Dask Name: dataframe-sum, 5 tasks

In [21]:
DfPlus = testDf.sum(axis=1)

In [22]:
DfPlus.head()

1    26310.0
2     1672.0
3    11147.0
4      854.0
5      148.0
dtype: float64

In [23]:
DfPlus.tail()

262     671.0
263     885.0
264     197.0
265    5160.0
266       4.0
dtype: float64

In [24]:
testDf['sum']= DfPlus

In [25]:
testDf.head(100)

,"Province/State, Country/Region",1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20,sum
1,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,575.0,542.0,683.0,748.0,656.0,556.0,664.0,761.0,783.0,26310.0
2,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17.0,36.0,42.0,44.0,31.0,48.0,57.0,69.0,82.0,1672.0
3,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,111.0,117.0,102.0,105.0,109.0,112.0,109.0,112.0,116.0,11147.0
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,854.0
5,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,4.0,17.0,5.0,12.0,8.0,2.0,2.0,6.0,148.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Djibouti,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,71.0,53.0,42.0,25.0,43.0,8.0,16.0,36.0,38.0,4539.0
97,Dominican Republic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,526.0,289.0,393.0,629.0,571.0,564.0,390.0,309.0,415.0,23686.0
98,Ecuador,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,258.0,539.0,523.0,0.0,1338.0,578.0,395.0,571.0,621.0,47943.0
99,Egypt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1365.0,1385.0,1455.0,1442.0,1577.0,1677.0,1618.0,1691.0,1567.0,47856.0
100,El Salvador,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,89.0,87.0,83.0,99.0,108.0,122.0,117.0,106.0,115.0,3941.0